### ISSUE TITLE
[Bug] ReviewMapper와 MyBatisReviewCommentRepository 에서 오류가 발생했어요

### ISSUE THREAD

**Issue by hgh1472** [prgrms-be-devcourse/NBE1_2_Team10#75]
# ❗❗ 발견한 버그에 대한 설명

**어떻게 해당 버그가 발생하는지 명확하게 설명해주세요.**

프로젝트 실행 시, `ReviewMapper.xml`에서 다음 오류가 발생했습니다
```text
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'file [C:\Users\hgh14\hwang\programmers\2_project\develop\application\build\resources\main\mappers\review\ReviewMapper.xml]'. Cause: java.lang.IllegalStateException: No typehandler found for property userId
	at app//org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:127)
	at app//org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:100)
	at app//org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:698)
	... 113 more
Caused by: java.lang.IllegalStateException: No typehandler found for property userId
	at org.apache.ibatis.mapping.ResultMapping$Builder.validate(ResultMapping.java:153)
	at org.apache.ibatis.mapping.ResultMapping$Builder.build(ResultMapping.java:140)
	at org.apache.ibatis.builder.MapperBuilderAssistant.buildResultMapping(MapperBuilderAssistant.java:352)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildResultMappingFromContext(XMLMapperBuilder.java:403)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:286)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:261)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElements(XMLMapperBuilder.java:253)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:123)
	... 115 more
```

이후 ReviewMapper를 따로 만져서 대충 넘어가보긴 했는데 다음에는 `MyBatisReviewCommentRepository`에서 오류가 발생했습니다.
```text
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalStateException: No typehandler found for property userId
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:83) ~[mybatis-spring-3.0.3.jar:3.0.3]
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[spring-tx-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802) ~[spring-beans-6.1.13.jar:6.1.13]
	... 44 common frames omitted
Caused by: java.lang.IllegalStateException: No typehandler found for property userId
	at org.apache.ibatis.mapping.ResultMapping$Builder.validate(ResultMapping.java:153) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.mapping.ResultMapping$Builder.build(ResultMapping.java:140) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.builder.MapperBuilderAssistant.buildResultMapping(MapperBuilderAssistant.java:352) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.applyResults(MapperAnnotationBuilder.java:468) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.applyResultMap(MapperAnnotationBuilder.java:257) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parseResultMap(MapperAnnotationBuilder.java:233) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:129) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:72) ~[mybatis-3.5.14.jar:3.5.14]
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:895) ~[mybatis-3.5.14.jar:3.5.14]
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80) ~[mybatis-spring-3.0.3.jar:3.0.3]
	... 47 common frames omitted
```
혹시 리뷰쪽에 추가적인 설정이 필요한걸까요??

---

# ✅ 정상적인 실행

**정상적으로 실행 시 예측되는 동작에 대해 서술해주세요.**

빈 생성하는 데에 오류가 발생해서 문제 되는 부분 수정해서 컴파일 가능하도록 하면 될 것 같습니다!

---

# 📤 문제 상황 공유

![image](https://github.com/user-attachments/assets/31630889-5f65-48aa-858f-582e122cbe1b)

`userId` 관련해서 파싱하는 데에 오류가 있는 것 같아요

---

**Comment by jbw9964** [comment]
어느 브랜치에서 작업하다 에러 발생했나요?

**Comment by jbw9964** [comment]
혹시 `config` 폴더에 `UUIDTypeHandler` 가 bean 으로 잘 등록되었을까요?

저는 `develop` 브랜치에서 실행하니 아예 다른 에러가 발생하네요.

**Comment by hgh1472** [comment]
develop에서 다시 받아와서 해보니까 되네요....
